CREATE TABLE Users (
    user_id NUMBER PRIMARY KEY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    username VARCHAR2(100) UNIQUE NOT NULL,
    profile_img VARCHAR2(500),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 자동 증가 SEQUENCE & TRIGGER 생성
CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER users_trigger
BEFORE INSERT ON Users
FOR EACH ROW
BEGIN
    SELECT users_seq.NEXTVAL INTO :NEW.user_id FROM DUAL;
END;
/
